Crdcdh 736 001 pgu
CBIIT/crdc-datahub-validator pull request #21
Opened 2024-01-10 19:53 UTC by vshand11

1.  change batch status from "Loaded" to "Uploaded"
2. change batch status from "Rejected" to "Failed"
3. update metadataValidationStatus of submission to "New" after metadata loaded to DB.
4. update metadataValidationStatus of submission to "Error" after metadata failed essential validation.

2024-01-10 21:49 UTC, knockknockyoo requested changes
One minor change, could you change the variable name for python name convention?

2024-01-11 14:26 UTC, vshand11 commented on src/essential_validator.py
> +                                submissionMetaStatus = STATUS_NEW
Updated, please review again, thank!

2024-01-11 15:41 UTC, n2iw approved these changes
LGTM

2024-01-11 15:45 UTC, knockknockyoo approved these changes

2024-01-11 15:45 UTC, merged