Implemented crdcdh-972
CBIIT/crdc-datahub-validator pull request #79
Opened 2024-03-26 13:42 UTC by vshand11

1. Implemented crdcdh-972
2. fixed crdcdh-966
3. fixed crdcdh-967

2024-03-27 14:55 UTC, n2iw requested changes

2024-03-27 15:55 UTC, vshand11 commented on src/metadata_validator.py
> +                result[ERRORS].append(create_error("Relationship not specified", f'{msg_prefix} Relationship to a “{parent_type}” node is not defined.'))
Updated.  And it is handled in new version of essential validator.

2024-03-27 15:55 UTC, vshand11 commented on src/metadata_validator.py
> +            result[ERRORS].append(create_error("Invalid relationship", f'{msg_prefix} No relationships specified.'))
Updated.

2024-03-28 16:00 UTC, n2iw approved these changes
LGTM

2024-03-28 16:00 UTC, merged